<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="user_tests"
    errors="1" failures="0" hostname="" id="" package="user_tests" skipped="0"
    tests="1" time="1.014" timestamp="Fri, 03 Nov 2017 19:47:11 GMT">
  
    <testcase name="Will I get error alert when trying to sign in with bad data" classname="user_tests" time="1.014" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [User Tests / Will I get error alert when trying to sign in with bad data]:

  ReferenceError: object is not defined
    at Object.userSignInFunc (/Users/AdamandStacyMartinez/Documents/DevMtn/Projects/perkNow-automation/nightwatch/test_data/user_functions.js:9:61)
    at Object.Will I get error alert when trying to sign in with bad data (/Users/AdamandStacyMartinez/Documents/DevMtn/Projects/perkNow-automation/nightwatch/testing/user_tests.js:24:23)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    </system-err>
  

  
  </testsuite>
</testsuites>
